### ISSUE TITLE
Điểm danh nhoaaa quý dị

### ISSUE THREAD

**Issue by BaoNhiB9PhuNhuan** [BaoNhiB9PhuNhuan/Lop-11A09-Nhom-6#1]

**Comment by ThienBao1412** [comment]
E hèm ... e hèm , hơi hack não xíu vì quá tr app nhưng ... T đã vào được và hoàn tất điểm danh - Võ Hồng Thiên Bảo - 07

**Comment by Duong0203** [comment]
Lê Quang Dương /14/B9

**Comment by HienCaoPhuNhuan** [comment]
Good nha @BaoNhiB9PhuNhuan hỗ trợ các nhóm khác nha
@tranquynhanh11a09 đăng kí bằng mail người khác con coi chừng lỡ có xác thực gì lại rắc rối
