### ISSUE TITLE
Bài 4 - Câu 1: Hãy cho biết số thứ tự dòng lệnh thuộc về những phần sau:

### ISSUE THREAD

**Issue by BaoNhiB9PhuNhuan** [BaoNhiB9PhuNhuan/Lop-11A09-Nhom-6#2]
### **PHẦN 1: KHAI BÁO**
- Khai báo thư viện
01 #include <SoftwareSerial.h>
- Khai báo hằng
02 #define BT_TRAIN 2
03 #define BT_RECEI 3
- Khai báo biến
06 int relay = 10;

### **PHẦN 2: THIẾT LẬP**
08 void setup ()
09 {
10 pinMode (replay, OUTPUT);
11 BlueTooth.begin(9600
12 }

### **PHẦN 3: VÒNG LẶP**
13 void loop ()
14 {
15 State = BlueTooh.read();
16 if (State==117) {  //177 là giá trị khi nhấn mũi tên lên 
17 digitalWrite (relay, HIGH); // relay bật đèn sáng
18 delay (1000);
19 }
20 if (State=100) {  //100 là giá trị khi nhấn mũi tên xuống
21 digitalWrite (relay, LOW); // relay ngắt đèn tắt
22 delay (1000);
23 }
24 }

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @NguyenHongDucB9 @ThienBao1412 @Duong0203 tui đã tạo issue để mình làm bài tập nhóm lần này rùi nha, **nhớ vào check thường xuyên á**. 
Mai tui sẽ hướng dẫn chi tiết dùng GitHub nha, ngâm cứu được 1 tiếng gòiii.

**Comment by ThienBao1412** [comment]
Hehe lại được on the mic rùi , tới giờ khùm đin , tính ga cũm dễ dùng chứ hã , mai là sẽ được nhóm trưởng chỉ bảo thêm các tính năng quan trọng cho việc học chứ khum phải việc on mic 😁 vô thường xuyên chắc là cứ rãnh rãnh sáng trưa chìu tối mỗi bủi zô check 2 3 lần zì đó phớ hôn . Này thì dễ , ngồi không có mần cái chi rựa , zô coi sẵn tìm hỉu cái ứng dụng đen đen này luôn 😁 mút úp bài zô cho nó easy game hehe , on mic thế đủ rùi nhường mic cho bạn khác nhaaa . Mng ngủ ngon 💯💯💯

**Comment by BaoNhiB9PhuNhuan** [comment]
@NguyenHongDucB9 @ThienBao1412 và tui sẽ làm câu 1 nhe
- Nhớ coi lại bài giảng hôm thứ 4 của thầy để dễ làm bài hơn nha
- Các bạn cứ thoải mái trao đổi trong đây rùi tui sẽ so sánh câu trả lời của mỗi người rùi gộp lại cho hoàn chỉnh nha
- **DEADLINE hoàn thành là 17h ngày mai (16/10)**

**Comment by BaoNhiB9PhuNhuan** [comment]
mọi người okee hongg

**Comment by tranquynhanh11a09** [comment]
<img src="https://i.pinimg.com/originals/6a/8a/93/6a8a93567a289f00b8ed65fd1cfe3bff.gif">

**Comment by ThienBao1412** [comment]
Um ... Hmmm , theo sự suy nghĩ và coi lại Record hum trước thì có dc cái đáp án như zị đây . Tự nhin thấy coá zài cái nó theo thứ tự lun í , khum bíc có nên đổi khum . Hơi sợ sai tí 🥺
Phần Khai Báo
Khai báo thư viện 
#01
Khai báo hằng 
#02
#03
Khai báo biến
#4
#5
#6
#7
Phần Thiết Lập 
#08
#09
#11
#10
#12
Phần Vòng Lập 
#13
#14
#16
#19
#17
#18
#20
#23
#21
#22
#15
#24
U là trời , cúi cùng cũng xongg 
Nộp bài đúm thời hạnnnn ❤️

**Comment by NguyenHongDucB9** [comment]
Phần khai báo
Khai báo thư viện
#1
Khai báo hằng
#2
#3
Khai báo biến
#4
#5
#6
#7
Phần thiết lập
#8
#9
#10
#11
#12
Phần vòng lặp
#13
#14
#16
#17
#18
#19
#20
#21
#22
#23
#15
#24
Sau khi nghe giảng lại thì tui thấy nó theo thứ tự, nên không biết trình bày v có đúng không:<<

**Comment by BaoNhiB9PhuNhuan** [comment]
à há 2 người này, seo lại trình bày y chang z hẻ, bữa nói là trình bày như z nè
vd Khai báo thư viện: 01
chú ý hơn nheee

**Comment by ThienBao1412** [comment]
Ủa ủa ulatr :))) tại thấy cái đó nó có để thăng , còn khum để thăng thì hoi 🥺 sửa lại nèee 
Khai báo 
Khai báo thư viện 01
Khai háo hằng 02,03
Khai báo biến 04,05,06,07
Thiết lập 
08,09,10,11,12
Vòng lập 13,14,15,16,17,18,19,20,21,22,23,24
Ahihi 😁 đúm r đúm r

**Comment by BaoNhiB9PhuNhuan** [comment]
### Tui tổng kết lại nha, mọi người nếu thấy oke thì react nhaaa
### **PHẦN 1: KHAI BÁO**
- Khai báo thư viện
01 #include <SoftwareSerial.h>
- Khai báo hằng
02 #define BT_TRAIN 2
03 #define BT_RECEI 3
- Khai báo biến
06 int relay = 10;

### **PHẦN 2: THIẾT LẬP**
08 void setup ()
09 {
10 pinMode (replay, OUTPUT);
11 BlueTooth.begin(9600
12 }

### **PHẦN 3: VÒNG LẶP**
13 void loop ()
14 {
15 State = BlueTooh.read();
16 if (State==117) {  //177 là giá trị khi nhấn mũi tên lên 
17 digitalWrite (relay, HIGH); // relay bật đèn sáng
18 delay (1000);
19 }
20 if (State=100) {  //100 là giá trị khi nhấn mũi tên xuống
21 digitalWrite (relay, LOW); // relay ngắt đèn tắt
22 delay (1000);
23 }
24 }

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @NguyenHongDucB9 @ThienBao1412 @Duong0203 dô coi oke thì react cái cmt tổng hợp nha

**Comment by BaoNhiB9PhuNhuan** [comment]
### **CHỐT ĐƠN CÂU 1 NHOAAAAAA**
