### ISSUE TITLE
Bài 4 - Câu 2: Cho biết sự khác nhau giữa hàm void setup() và void loop()

### ISSUE THREAD

**Issue by BaoNhiB9PhuNhuan** [BaoNhiB9PhuNhuan/Lop-11A09-Nhom-6#3]
### **Void setup()**
- Dùng để **thiết lập cho một chương trình**  (cụ thể là thiết lập tốc độ truyền dữ liệu, hoặc xác định kiểu chân ra hay vào)
- Nó sẽ chạy và thực hiện các lệnh **chỉ 1 lần** khi Arduino được cấp nguồn hoặc reset

### **Void loop()**
- Dùng để v**iết các lệnh điều khiển chương trình** để thực hiện nhiệm vụ mà chúng ta muốn
- Nó sẽ chạy sau khi hàm setup() chạy xong và trong tiếng Việt loop nghĩa là vòng lặp thì nó sẽ chạy **lặp đi lặp lại** cho tới khi chúng ta ngắt nguồn

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @Duong0203 sẽ làm câu 2 nha
- Nhớ coi lại bài giảng hôm thứ 4 của thầy để dễ làm bài hơn nha
- Các bạn cứ thoải mái trao đổi trong đây rùi tui sẽ so sánh câu trả lời của mỗi người rùi gộp lại cho hoàn chỉnh nha
- **DEADLINE hoàn thành là 17h ngày mai (16/10)**

**Comment by Duong0203** [comment]
set up là chạy một lần
loop là chạy lặp lại đến khi ngắt điện
vold set up // các câu lênh thiết lập của thiết bị
vold loop // các câu lênh điều khiển của thiết bị

**Comment by tranquynhanh11a09** [comment]
hmmm sau khi đọc câu hỏi, xem lại video bài giảng trên lớp và kết hợp với thông tin từ trên google, sau đây là những gì tui hiểu

## Hàm setup()

Đúng như cái tên, hàm này sẽ dùng để **thiết lập cho một chương trình** (cụ thể là thiết lập tốc độ truyền dữ liệu, hoặc xác định kiểu chân ra hay vào); nó sẽ chạy và thực hiện các lệnh chỉ **1 lần** khi Arduino được cấp nguồn hoặc reset

## Hàm loop()

Hàm này sẽ dùng để viết các lệnh **điều khiển chương trình** để thực hiện nhiệm vụ mà chúng ta muốn; nó sẽ chạy sau khi hàm setup() chạy xong và với loop trong tiếng Việt nghĩa là vòng lặp thì nó sẽ chạy **lặp đi lặp lại** cho tới khi chúng ta ngắt nguồn

### Nói dài dòng quá, nói chung tui đồng ý với ý kiến của Dương á nha =))))))))

**Comment by BaoNhiB9PhuNhuan** [comment]
### Tui chốt lại câu 2 lun nè, nếu mà oke thì react để tui tổng hợp lại hoàn thiện nhaa

### **Void setup()**
- Dùng để **thiết lập cho một chương trình (cụ** thể là thiết lập tốc độ truyền dữ liệu, hoặc xác định kiểu chân ra hay vào)
- Nó sẽ chạy và thực hiện các lệnh **chỉ 1 lần** khi Arduino được cấp nguồn hoặc reset

### **Void loop()**
- Dùng để v**iết các lệnh điều khiển chương trình** để thực hiện nhiệm vụ mà chúng ta muốn
- Nó sẽ chạy sau khi hàm setup() chạy xong và trong tiếng Việt loop nghĩa là vòng lặp thì nó sẽ chạy **lặp đi lặp lại** cho tới khi chúng ta ngắt nguồn

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @NguyenHongDucB9 @ThienBao1412 @Duong0203 dô coi oke thì react cái cmt tổng hợp nha

**Comment by BaoNhiB9PhuNhuan** [comment]
### **CHỐT ĐƠN CÂU 2 LUN NÈEE**
