### ISSUE TITLE
Bài 6 - Phân công và thảo luận 7 câu hỏi

### ISSUE THREAD

**Issue by BaoNhiB9PhuNhuan** [BaoNhiB9PhuNhuan/Lop-11A09-Nhom-6#5]
1. Các bước giải 1 bài toán tin học? 
2. Board mạch Arduino chỉ xử lý 2 dạng tín hiệu nào?
3. Liệt kê các chân điều khiển tín hiệu Digital trên Arduino?
4. Trên Arduino, chân nối đất là chân nào?
5. Board mạch Arduino Uno có thể cấp nguồn điện tối đa bao nhiêu Vol?
6. Đèn Led có hiệu điện thế dao động ở mức (1.9 - 3.2V)
7. Chức năng của điện trở

**Comment by BaoNhiB9PhuNhuan** [comment]
### hú hú nhiệm vụ mới tới ròi mụi người @tranquynhanh11a09 @NguyenHongDucB9  @ThienBao1412  @Duong0203

**Comment by BaoNhiB9PhuNhuan** [comment]
Trưa mai tui sẽ gửi phân công nhooo, mọi người cố gắng chạy deadline xong sớm rùi nghỉ phẻ nèee

**Comment by BaoNhiB9PhuNhuan** [comment]
### **9h tối nay cả nhóm mình rảnh hết honggg** @tranquynhanh11a09  @NguyenHongDucB9  @ThienBao1412  @Duong0203

**Comment by tranquynhanh11a09** [comment]
rảnh ọ

**Comment by tranquynhanh11a09** [comment]
t zẫn kh zô dc cái tinkercard trên pc btw
![image](https://user-images.githubusercontent.com/91965972/140255755-4faae6e6-3d8c-49f6-9986-c74693cafd6b.png)

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 nó đơ quài hong cho dô hã

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @NguyenHongDucB9 @ThienBao1412  @Duong0203 tối nay 9h nhào dô GitHub thảo luận ròi làm xong trong tối nayyy lun nha

**Comment by tranquynhanh11a09** [comment]
> @tranquynhanh11a09 nó đơ quài hong cho dô hã

đrui

**Comment by tranquynhanh11a09** [comment]
> @tranquynhanh11a09 @NguyenHongDucB9 @ThienBao1412 @Duong0203 tối nay 9h nhào dô GitHub thảo luận ròi làm xong trong tối nayyy lun nha

![image](https://user-images.githubusercontent.com/91965972/140290971-142ab62d-3f8f-4358-b7b4-c3c9bb6b0b18.png)

**Comment by ThienBao1412** [comment]
Á à oce nhó :))))))))))
Cứ được on mic miết thế này ngại quó ngại quó 😁😁😁

**Comment by tranquynhanh11a09** [comment]
tui nôn dc làm quá nè mn oi
![image](https://user-images.githubusercontent.com/91965972/140311478-850193d2-f8c2-40b7-a189-039515d1833b.png)

**Comment by ThienBao1412** [comment]
Ố tà tà tới h ròi bắt đầu chưa cạ nhạ iu của em 😘

**Comment by BaoNhiB9PhuNhuan** [comment]
ai có mặt đỉm danhh đê

**Comment by Duong0203** [comment]
oke

**Comment by tranquynhanh11a09** [comment]
dô nèo

**Comment by BaoNhiB9PhuNhuan** [comment]
BẮT ĐẦU NHA MỌI NGƯỜI, TẤT CẢ ĐỀU LÀM 7 CÂU HẾT NHOAAA

**Comment by ThienBao1412** [comment]
Há há z tính ga t cmt đầu tiên là t có mặt đầu tiên , quá pro vip No1 :)))

**Comment by BaoNhiB9PhuNhuan** [comment]
CÂU 1: 9H22 Là cmt câu trả lời của mn nha

**Comment by tranquynhanh11a09** [comment]
ê cnay học quài học từ lớp 10 tới đầu lớp 11 lun

**Comment by ThienBao1412** [comment]
Ủa sao t nhìn thấy quen z hình như nhớ mang máng học ở đâu rùi á

**Comment by tranquynhanh11a09** [comment]
bài 1 hay sao đó cha

**Comment by ThienBao1412** [comment]
Bài 1 phớ hôn zị , mới học hồi đầu năm nè u là trời 😁

**Comment by BaoNhiB9PhuNhuan** [comment]
GÒI GÒI CHO THÊM 3' NỮA tới 9h25

**Comment by tranquynhanh11a09** [comment]
**Bước 1** : Xác định bài toán
**Bước 2** : Lựa chọn và xây dựng thuật toán
**bước 3** : Lập trình 
**Buowsc4** : Hiệu chỉnh
**Bước 5** : Viết tài liệu

**Comment by ThienBao1412** [comment]
Bước 1 là xác định bài Tón nhé
Bước 2 là tìm cấu trúc dữ liệu để mà thiết kế được cái thuật Tón để mà còn giả
Bước 3 là tìm thuật toán
Bước 4 nó sẽ là lập trình , là lập trình cái cái thuật toán mà mình tìm được ở bước 3 .
Zà cúi cùng là bước 5 , chỉnh sửa zà kỉm tra cái thuật Tón lại cho hoàn chỉnh thui
Úi giời , game là dễ 💯💯💯
Kiếm điểm cái trái đào này z 🍑 nó gất là ngon ăn và dễ dàng :))

**Comment by tranquynhanh11a09** [comment]
ê t type trên pc lâu như quỷ

**Comment by tranquynhanh11a09** [comment]
sogi nka

**Comment by tranquynhanh11a09** [comment]
Bảo nó search gg chắc kèo luôn =))))))

**Comment by BaoNhiB9PhuNhuan** [comment]
Ủa Bảo game là dễ mà chỉnh nhìu zzzz

**Comment by ThienBao1412** [comment]
Ơ kìa , tui coi của bạn nữa đó :)))

**Comment by BaoNhiB9PhuNhuan** [comment]
> ê t type trên pc lâu như quỷ

khummmsaooo

**Comment by ThienBao1412** [comment]
Xong gòi tui e đít lại cái còm men

**Comment by NguyenHongDucB9** [comment]
Bước 1 là xác định bài Tón nhé
Bước 2 là tìm cấu trúc dữ liệu để mà thiết kế được cái thuật Tón để mà còn giả
Bước 3 là tìm thuật toán
Và cúi cùng là bước 4 nó sẽ là lập trình , là lập trình cái cái thuật toán mà mình tìm được ở bước 3

**Comment by ThienBao1412** [comment]
Chứ gu gồ nó dỏm quá sai quá trời 😏

**Comment by tranquynhanh11a09** [comment]
suỵt bạn có quyền giữ im lặng trc khi bị quê

**Comment by ThienBao1412** [comment]
> Ủa Bảo game là dễ mà chỉnh nhìu zzzz
> 

:))))))) Tại cái gu gồ của tui nó dỏm quá tính làm đờ phờ lát còm men đầu tiên cho nó ngầu như cái bồn cầu luôn mà nó làm que^ muốn đội cái quần lên đầu luôn

**Comment by Duong0203** [comment]
Bước 1 : Xác định bài toán
Bước 2 : Lựa chọn và xây dựng thuật toán
bước 3 : Lập trình
Buowsc4 : Hiệu chỉnh
Bước 5 : Viết tài liệu
sai thì thui nha

**Comment by BaoNhiB9PhuNhuan** [comment]
aukeee đủ câu 1

**Comment by ThienBao1412** [comment]
> suỵt bạn có quyền giữ im lặng trc khi bị quê
> 
Que^ 1 lần thoi à nha 😏 , câu 2 teo sẽ zượt mặt cho m sem 😏

**Comment by BaoNhiB9PhuNhuan** [comment]
Câu 1:
Bước 1 : Xác định bài toán
Bước 2 : Lựa chọn và xây dựng thuật toán
bước 3 : Lập trình
Bước 4 : Hiệu chỉnh
Bước 5 : Viết tài liệu

**Comment by BaoNhiB9PhuNhuan** [comment]
CÂU 2: 9H33 nha

**Comment by tranquynhanh11a09** [comment]
Câu 2 thì t nhớ lúc làm ktra t chọn câu nó xử lí dc dạng tín hiệu analog zí digital á

**Comment by tranquynhanh11a09** [comment]
còn đáp án chính xác t kh nhớ nma t làm z

**Comment by ThienBao1412** [comment]
Có 2 dạng tính hiệu là Digital và Analog

**Comment by BaoNhiB9PhuNhuan** [comment]
câu này bữa ktra có nha quý dị

**Comment by Duong0203** [comment]
Digital và Analog phải khum nhỉ

**Comment by tranquynhanh11a09** [comment]
típ típ i

**Comment by NguyenHongDucB9** [comment]
hai loại tính hiệu digital và analog

**Comment by ThienBao1412** [comment]
Bữa mứi ktra lun làm sao mà sai được , bài tui được tận 925 đỉm đóoo mng cứ copy đi nhaaa

**Comment by BaoNhiB9PhuNhuan** [comment]
ròi đủ câu 2

**Comment by BaoNhiB9PhuNhuan** [comment]
Câu 2: Digital và Analog

**Comment by Duong0203** [comment]
Oce nhá

**Comment by BaoNhiB9PhuNhuan** [comment]
CÂU 3: 9H40 NHA

**Comment by BaoNhiB9PhuNhuan** [comment]
Câu này hình như ở bài 2 đóa mn

**Comment by tranquynhanh11a09** [comment]
chân từ 0 tới 13 for sure 
![image](https://user-images.githubusercontent.com/91965972/140333535-67844f60-0208-4ec1-82f8-d620f0666a4e.png)

**Comment by Duong0203** [comment]
Chân 1~13

**Comment by ThienBao1412** [comment]
Hôm trước cũng ktra câu này nè
Sao mà EZ z hỏi câu nào khó hơn đi trầu , nhắm mắt trl cũng đúm nữa
0 đến 13 nhó 😘

**Comment by NguyenHongDucB9** [comment]
chân 0-13 nhá:))

**Comment by BaoNhiB9PhuNhuan** [comment]
xong câu 3 nhó

**Comment by BaoNhiB9PhuNhuan** [comment]
Câu 3: chân số 0 đến 13

**Comment by BaoNhiB9PhuNhuan** [comment]
CÂU 4: 9H43 NHA

**Comment by BaoNhiB9PhuNhuan** [comment]
Search chị gút gồ liền nèo

**Comment by tranquynhanh11a09** [comment]
ê cnay t kh biết đáp án nên t search gg cái nó ra GND á

**Comment by ThienBao1412** [comment]
Câu này cũm zẫn còn dễ nhak hôm trước cái bài ôn trên lớp học thầy có cho câu này nhưng khoanh sai và thầy đã cho kết quả đúng là GND nhó , teo làm trên đó đúm dc 68 câu  lận đó nha EZ gameeee 🙆🙆🙆

**Comment by Duong0203** [comment]
GND cj gg nói v

**Comment by NguyenHongDucB9** [comment]
GND nha

**Comment by BaoNhiB9PhuNhuan** [comment]
xong câu 4 nhooo

**Comment by BaoNhiB9PhuNhuan** [comment]
Câu 4: chân GND

**Comment by BaoNhiB9PhuNhuan** [comment]
CÂU 5: 9H47 NHA

**Comment by tranquynhanh11a09** [comment]
câu này ktra mấy lần t chọn 3-5.5 V á

**Comment by Duong0203** [comment]
3-5.5V nhể

**Comment by NguyenHongDucB9** [comment]
tối đa 5,5V

**Comment by tranquynhanh11a09** [comment]
ủa ê đọc đề kh kĩ

**Comment by tranquynhanh11a09** [comment]
tối đa 5.5V é

**Comment by tranquynhanh11a09** [comment]
cuê ...

**Comment by ThienBao1412** [comment]
Ũa t tưởng 12 😃 bữa đọc câu nào nó chạy 7-12 gì đó ũa mình lộn câu ròi hã ta

**Comment by BaoNhiB9PhuNhuan** [comment]
xong câu 5, tối đa thuiii đó nhaa nãy saiii á

**Comment by ThienBao1412** [comment]
Que^ thiệt sự 🥲

**Comment by BaoNhiB9PhuNhuan** [comment]
Câu 5: tối đa 5.5 Vol

**Comment by tranquynhanh11a09** [comment]
ủa câu 6 nó hỏi cgi z

**Comment by BaoNhiB9PhuNhuan** [comment]
CÂU 6: 9H51 NHA

**Comment by tranquynhanh11a09** [comment]
mn ới

**Comment by tranquynhanh11a09** [comment]
câu 6 nó có đáp án lun hay sao kìa

**Comment by NguyenHongDucB9** [comment]
là loại đèn sử dụng hiệu điện thế 1,9-3,2V

**Comment by ThienBao1412** [comment]
Ũa nó hỏi jztr tui tưởng nó hỏi là loại đèn Led nào mà sao lên gú gồ nó là cái câu hỏi lun ròi z tr

**Comment by Duong0203** [comment]
Đèn led hử

**Comment by BaoNhiB9PhuNhuan** [comment]
tui search là đèn led 5V

**Comment by BaoNhiB9PhuNhuan** [comment]
Câu 6: Đèn Led nào có hiệu điện thế dao động ở mức 1.9 - 3.2V

**Comment by tranquynhanh11a09** [comment]
ùa z Nhi chốt đáp án lun i

**Comment by BaoNhiB9PhuNhuan** [comment]
qua câu 7 nha, lát vòng lại câu 6

**Comment by NguyenHongDucB9** [comment]
Khống chế dòng điện qua tải cho phù hợp
Mắc điện trở thành cầu phân áp
Phân cực cho bóng bán dẫn hoạt động 
Tham gia vào các mạch tạo dao động R C sử dụng NE555
câu 7 nha

**Comment by BaoNhiB9PhuNhuan** [comment]
CÂU 7: 10H NHA

**Comment by ThienBao1412** [comment]
10h sáng mai hã :))) hay là 22h tối mai 🥺 sao deadline xa z

**Comment by BaoNhiB9PhuNhuan** [comment]
chời đất quơi 10h tối nay

**Comment by BaoNhiB9PhuNhuan** [comment]
còn 2' kìa làm lẹ iiii

**Comment by tranquynhanh11a09** [comment]
điện trở thì nó dùng để cản trở dòng điện thui chứ lèm gì, kiểu nơi sản xuất điện sản xuất ra 300kv xong chuyển xuống nhà dân mà nhà dân chỉ dùng được 220v nên phải gắn điện trở dô để phù hợp á kh là quá tải nó nổ banh chành 
![image](https://user-images.githubusercontent.com/91965972/140337826-215fe892-a6f2-408a-8329-c595d9a1cb60.png)

**Comment by ThienBao1412** [comment]
> gia

Ủa seo search gu gồ thíu 3 chấm cúi zòi z paste phải paste cho tới chớ

**Comment by BaoNhiB9PhuNhuan** [comment]
10h 1 phút ròi

**Comment by BaoNhiB9PhuNhuan** [comment]
tingg tongg giờ lành đã điểm, câu trl đâu hết rùi

**Comment by Duong0203** [comment]
Mắc điện trở thành cầu phân áp để có được một điện áp theo ý muốn từ một điện áp cho trước.
Phân cực cho bóng bán dẫn hoạt động.
Tham gia vào các mạch tạo dao động R C
Điều chỉnh cường độ dòng điện đi qua các thiết bị điện.
Tạo ra nhiệt lượng trong các ứng dụng cần thiết.
Tạo ra sụt áp trên mạch khi mắc nối tiếp 
Teo sợt nó ga vậy á

**Comment by tranquynhanh11a09** [comment]
ê câu trl của t đơn giản súc tích lun á

**Comment by ThienBao1412** [comment]
Câu nì mình học bên Lí có mà nhể sao nó chuyển nghề qua môn Tin luôn zòi z trời con này là Điện trở , theo cái tên thì định nghĩa nó cũm z , điện là dòng điện trở là cản trở dùng để cản trở dòng điện 😏 trùm Tón Lí Hoá lớp 8 , 9 nhó , khét tiếng nhất trường cấp 2 với điểm thi Tón Tuyển Sinh 9.75 nhó nhưng nó chỉ là quá khứ với hiện tại thi Toán còn có 5.5 🥲 
Ũa chết cha lạc đề , thì tóm cái váy lại thì nó là cản trở dòng điện á , hồi đó học là z , còn có cái gần giống nó nữa là biến trở nma hoi đang hỏi điện trở mà nên kệ nó đi ha 😀

**Comment by tranquynhanh11a09** [comment]
như vật lý lớp 9 á

**Comment by BaoNhiB9PhuNhuan** [comment]
Câu 7:
Khống chế dòng điện quá tải cho phù hợp.
Điều chỉnh cường độ dòng điện đi qua các thiết bị điện.
Phân cực cho bóng bán dẫn hoạt động.
Tham gia vào các mạch tạo dao động R C.
Mắc điện trở thành cầu phân áp để có được một điện áp theo ý muốn từ một điện áp cho trước.
Tạo ra nhiệt lượng trong các ứng dụng cần thiết.
Tạo ra sụt áp trên mạch khi mắc nối tiếp.

**Comment by tranquynhanh11a09** [comment]
> > suỵt bạn có quyền giữ im lặng trc khi bị quê
> 
> Que^ 1 lần thoi à nha smirk , câu 2 teo sẽ zượt mặt cho m sem smirk

ủa alo bạn ơi nãy h bạn chưa vượt mặt mình dc đók bạn ơi =))))))

**Comment by ThienBao1412** [comment]
> > > suỵt bạn có quyền giữ im lặng trc khi bị quê
> > 
> > Que^ 1 lần thoi à nha smirk , câu 2 teo sẽ zượt mặt cho m sem smirk
> 
> ủa alo bạn ơi nãy h bạn chưa vượt mặt mình dc đók bạn ơi =))))))

Não toi bị lag bạn ơi 🥲 nay não toi nó rơi ròi hay nó đi du lịch luôn ròi , tấu hài được hoi kiến thức nó theo gió cuốn đi ròi , hic ...

**Comment by BaoNhiB9PhuNhuan** [comment]
ròi quay câu 6

**Comment by BaoNhiB9PhuNhuan** [comment]
ròi qua tới câu 6 immm ruuuuu

**Comment by tranquynhanh11a09** [comment]
không có hỉu đề lun á bà

**Comment by ThienBao1412** [comment]
Quay lại nma câu hõi nó là zì z 🥲 tui tưởng nó là câu trạ lợi 🥺

**Comment by tranquynhanh11a09** [comment]
hnhu cdo đáp lun

**Comment by tranquynhanh11a09** [comment]
t nghĩ thầy mún cho câu hỏi "đèn Led có hiệu điện thế dao động ở mức nào?" á

**Comment by ThienBao1412** [comment]
Hay là mình tạm gác lại âu lo cùng với  DaLAB và Miu Lê , mình hỏi thầy lại luôn i chứ hỏng hiểu câu hỏi . Còn ét lai thì nó dí quá nè 😭😭😭

**Comment by tranquynhanh11a09** [comment]
ê thức đêm làm t đói gke nè 
![image](https://user-images.githubusercontent.com/91965972/140341432-1b353f20-a954-4956-a872-c948822b1e39.png)

**Comment by BaoNhiB9PhuNhuan** [comment]
đang đợi...... thầy rep...........

**Comment by BaoNhiB9PhuNhuan** [comment]
Thầy nghĩ là ý cô hỏi vậy nếu vậy thì khi lắp đèn vào mạch thì cần gì hay ko để đèn sáng bình thường
- Thầy Hiền đtrai rep ạ -

**Comment by tranquynhanh11a09** [comment]
thì cần hiệu điện thế ở hai đầu dao động trg mức từ 1.9V - 3.2V chứ seo

**Comment by tranquynhanh11a09** [comment]
giống cái U định mức học ở lớp 9

**Comment by ThienBao1412** [comment]
> ê thức đêm làm t đói gke nè 
> ![image](https://user-images.githubusercontent.com/91965972/140341432-1b353f20-a954-4956-a872-c948822b1e39.png)
> 

Ủa làm sao để có hình ảnh z tui hong làm đượt

**Comment by tranquynhanh11a09** [comment]
10k đi t nói cho

**Comment by ThienBao1412** [comment]
> 10k đi t nói cho

Sao pạn zật chất z , tui cũng muốn cống hiến những tấm mêm cho mng sem mà 🥲

**Comment by BaoNhiB9PhuNhuan** [comment]
Vì đèn LED có hiệu điện thế hoạt động khá thấp, tùy loại đèn LED mà hiệu điện thế dao động ở mức (1.9 – 3.2 V).Vì vậy, khi bạn chạy ở hiệu điện thế 5V, thì bạn cần sử dụng một điện trở để giảm hiệu điện thế vào LED.

**Comment by Duong0203** [comment]
Gg khum có lun á

**Comment by BaoNhiB9PhuNhuan** [comment]
VẬY CHỐT HẾT NHAAAAA

**Comment by ThienBao1412** [comment]
> Vì đèn LED có hiệu điện thế hoạt động khá thấp, tùy loại đèn LED mà hiệu điện thế dao động ở mức (1.9 – 3.2 V).Vì vậy, khi bạn chạy ở hiệu điện thế 5V, thì bạn cần sử dụng một điện trở để giảm hiệu điện thế vào LED. 

Tóm tắt z thầy có bắt bẻ mình khum 🥺 mình có nên sợt gu gồ câu trả lời đầy đủ lun khum

**Comment by BaoNhiB9PhuNhuan** [comment]
> > Vì đèn LED có hiệu điện thế hoạt động khá thấp, tùy loại đèn LED mà hiệu điện thế dao động ở mức (1.9 – 3.2 V).Vì vậy, khi bạn chạy ở hiệu điện thế 5V, thì bạn cần sử dụng một điện trở để giảm hiệu điện thế vào LED.
> 
> Tóm tắt z thầy có bắt bẻ mình khum 🥺 mình có nên sợt gu gồ câu trả lời đầy đủ lun khum

z sợt típ iii

**Comment by BaoNhiB9PhuNhuan** [comment]
Với các loại đèn LED có hiệu điện thế nhỏ thì bạn mắc nối tiếp ở chân dương của bé LED một điện trở có trị số khoảng 560 – 1000 Ohm, còn các LED có hiệu điện thế lớn hơn thì bạn mắc với điện trở nhỏ hơn chẳng hạn từ 220 – 560 Ohm.

**Comment by ThienBao1412** [comment]
> Với các loại đèn LED có hiệu điện thế nhỏ thì bạn mắc nối tiếp ở chân dương của bé LED một điện trở có trị số khoảng 560 – 1000 Ohm, còn các LED có hiệu điện thế lớn hơn thì bạn mắc với điện trở nhỏ hơn chẳng hạn từ 220 – 560 Ohm.

Ulatr bạn copy paste lẹ z , mình còn đang sợt . Có ròi thì khum sợ thầy bắt ... bẻ ... cổ ròi 😊

**Comment by BaoNhiB9PhuNhuan** [comment]
RÒI CHỐT LẦN CUỐI

**Comment by BaoNhiB9PhuNhuan** [comment]
mọi người ngủ ngonnn nha

**Comment by BaoNhiB9PhuNhuan** [comment]
sáng mai 7h dậy dô react cái tổng hợp cuối cùng của tất cả các câu nhaaa

**Comment by tranquynhanh11a09** [comment]
oce z tui xin phép đi tắm nho tắm trễ đột quỵ xỉu
![image](https://user-images.githubusercontent.com/91965972/140349796-8a45aa34-b138-42cf-9e4e-952c19b87296.png)

**Comment by NguyenHongDucB9** [comment]
mng ngủ ngon

**Comment by ThienBao1412** [comment]
Ulatr mai 7h45 mứi học ạ 🥲 dậy reac xong đi ngủ típ 😁😁 chứ khum thoi là khỏi thức tỉnh bản năng zô cực ( Ultra Instic ) như Gô Ku luôn 🥲

**Comment by BaoNhiB9PhuNhuan** [comment]
> oce z tui xin phép đi tắm nho tắm trễ đột quỵ xỉu ![image](https://user-images.githubusercontent.com/91965972/140349796-8a45aa34-b138-42cf-9e4e-952c19b87296.png)

gì tắm trễ quá z bàa

**Comment by ThienBao1412** [comment]
> oce z tui xin phép đi tắm nho tắm trễ đột quỵ xỉu
> ![image](https://user-images.githubusercontent.com/91965972/140349796-8a45aa34-b138-42cf-9e4e-952c19b87296.png)
> 

Ũa zị chứ 10 gưỡi là còn sớm hã pà

**Comment by ThienBao1412** [comment]
![received_1267207033704022.jpeg](https://user-images.githubusercontent.com/91998962/140351829-0cf883f2-d591-4800-9fb8-dc62e44e45d2.jpeg) 
Cái nì tặng mng nhó 😁😁😁

**Comment by BaoNhiB9PhuNhuan** [comment]
@HienCaoPhuNhuan hihiii nhóm con mới thảo luận xongg đó, zzz là tốt chưaaaaa thầyyyyy

**Comment by ThienBao1412** [comment]
Hó hó đi kiếm cái nì nãy giờ . Chúc lại mng nè , gút naiiiiiiii

**Comment by BaoNhiB9PhuNhuan** [comment]
Mai tui gửi lại cái tổng hợp 7 câu sau nha, bùn ngủ quó, bái baii mn

**Comment by HienCaoPhuNhuan** [comment]
ủa tag hồi nào ko biết :(

**Comment by BaoNhiB9PhuNhuan** [comment]
> ủa tag hồi nào ko biết :(

Thầy mún biết honggg @HienCaoPhuNhuan @HienCaoPhuNhuan @HienCaoPhuNhuan 
3 lần cho đủ lunnn nha thầy

**Comment by BaoNhiB9PhuNhuan** [comment]
### **1. Các bước giải 1 bài toán tin học?**
- Bước 1 : Xác định bài toán.
- Bước 2 : Lựa chọn và xây dựng thuật toán.
- Bước 3 : Lập trình.
- Bước 4 : Hiệu chỉnh.
- Bước 5 : Viết tài liệu.
### **2. Board mạch Arduino chỉ xử lý 2 dạng tín hiệu nào?**
- Board mạch Arduino chỉ xử lý 2 dạng tín hiệu: Digital và Analog.
### **3. Liệt kê các chân điều khiển tín hiệu Digital trên Arduino?**
- Các chân điều khiển tín hiệu Digital trên Arduino: chân số 0 đến 13.
### **4. Trên Arduino, chân nối đất là chân nào?**
- Trên Arduino, chân nối đất là chân GND.
### **5. Board mạch Arduino Uno có thể cấp nguồn điện tối đa bao nhiêu Vol?**
- Board mạch Arduino Uno có thể cấp nguồn điện tối đa 5.5 Vol.
### **6. Đèn Led có hiệu điện thế dao động ở mức (1.9 - 3.2V)**
- Đèn LED có hiệu điện thế hoạt động khá thấp, tùy loại đèn LED mà hiệu điện thế dao động ở mức (1.9 – 3.2 V) vì vậy, khi bạn chạy ở hiệu điện thế 5V, thì bạn cần sử dụng một điện trở để giảm hiệu điện thế vào LED. Với các loại đèn LED có hiệu điện thế nhỏ thì mắc nối tiếp ở chân dương của đèn LED một điện trở có trị số khoảng 560 – 1000 Ohm, còn các đèn LED có hiệu điện thế lớn hơn thì bạn mắc với điện trở nhỏ hơn chẳng hạn từ 220 – 560 Ohm.
### **7. Chức năng của điện trở**
- Khống chế dòng điện quá tải cho phù hợp.
- Điều chỉnh cường độ dòng điện đi qua các thiết bị điện.
- Phân cực cho bóng bán dẫn hoạt động.
- Tham gia vào các mạch tạo dao động R C.
- Mắc điện trở thành cầu phân áp để có được một điện áp theo ý muốn từ một điện áp cho trước.
- Tạo ra nhiệt lượng trong các ứng dụng cần thiết.
- Tạo ra sụt áp trên mạch khi mắc nối tiếp.

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @NguyenHongDucB9  @ThienBao1412  @Duong0203 có CHỐT r nha, nếu oke hết thì react bla bla, còn có vấn đề gì nữa thì cứ cmt típ nhooo

**Comment by ThienBao1412** [comment]
> @tranquynhanh11a09 @NguyenHongDucB9  @ThienBao1412  @Duong0203 có CHỐT r nha, nếu oke hết thì react bla bla, còn có vấn đề gì nữa thì cứ cmt típ nhooo

Ulatr nghe hẹn 7h sáng mà sao hơn 12h đim chốt ròi :))) haha tui vẫn còn thức và chắc chắn tui là người nhanh nhất react và repply cmt nhó![42c13eb0b859013df504635af75c7403.gif](https://user-images.githubusercontent.com/91998962/140387396-e1f91d21-ce68-4c36-92a8-5b4266ffbdcd.gif)
Gút naii cạ nhạ nhẹ 👻❤️

**Comment by BaoNhiB9PhuNhuan** [comment]
> > @tranquynhanh11a09 @NguyenHongDucB9  @ThienBao1412  @Duong0203 có CHỐT r nha, nếu oke hết thì react bla bla, còn có vấn đề gì nữa thì cứ cmt típ nhooo
> 
> Ulatr nghe hẹn 7h sáng mà sao hơn 12h đim chốt ròi :))) haha tui vẫn còn thức và chắc chắn tui là người nhanh nhất react và repply cmt nhó![42c13eb0b859013df504635af75c7403.gif](https://user-images.githubusercontent.com/91998962/140387396-e1f91d21-ce68-4c36-92a8-5b4266ffbdcd.gif) Gút naii cạ nhạ nhẹ 👻❤️

thì tui gửi để sẵn zz đó, sáng dô ai thấy thì react thuii

**Comment by BaoNhiB9PhuNhuan** [comment]
CHỐT ĐƠN HẾT NHOAAA

**Comment by BaoNhiB9PhuNhuan** [comment]
### @tranquynhanh11a09 @NguyenHongDucB9  @ThienBao1412  @Duong0203 thích làm thảo luận giống đợt này hay đợt trước nèeee

**Comment by BaoNhiB9PhuNhuan** [comment]
### @HienCaoPhuNhuan dạ nhóm 6 - 11A9 xong project bài 6 ròi nha thầy

**Comment by ThienBao1412** [comment]
> ### @tranquynhanh11a09 @NguyenHongDucB9  @ThienBao1412  @Duong0203 thích làm thảo luận giống đợt này hay đợt trước nèeee

Như z lẹ hơn nè , mần z điiiii

**Comment by HienCaoPhuNhuan** [comment]
Nhanh quá, sợ 😢😢😢

**Comment by tranquynhanh11a09** [comment]
> ### @tranquynhanh11a09 @NguyenHongDucB9 @ThienBao1412 @Duong0203 thích làm thảo luận giống đợt này hay đợt trước nèeee

đợt này ọ

**Comment by ThienBao1412** [comment]
![received_368438701012395.jpeg](https://user-images.githubusercontent.com/91998962/142765543-2d0697a8-c515-4c7b-afb6-6af6d347fcea.jpeg)
Cho mụi ngừi mốt thả thính cờ rút nè 😘
