### ISSUE TITLE
Thảo luận cách lắp mạch và code mô phỏng đèn giao thông (activity trên Tinkercad)

### ISSUE THREAD

**Issue by BaoNhiB9PhuNhuan** [BaoNhiB9PhuNhuan/Lop-11A09-Nhom-6#6]

**Comment by tranquynhanh11a09** [comment]
ủa cí này làm cá nhân hay nhóm zạ

**Comment by BaoNhiB9PhuNhuan** [comment]
> ủa cí này làm cá nhân hay nhóm zạ

cái này là thảo luận nhóm xong qua tinkercard làm cá nhân nha bà

**Comment by BaoNhiB9PhuNhuan** [comment]
### **Ngày mai 14/11 mọi người rảnh giờ nào thì react cmt giờ đó nha**

**Comment by BaoNhiB9PhuNhuan** [comment]
10h - 11h30

**Comment by BaoNhiB9PhuNhuan** [comment]
12h-13h30

**Comment by BaoNhiB9PhuNhuan** [comment]
15h-16h30

**Comment by BaoNhiB9PhuNhuan** [comment]
19h-20h30

**Comment by BaoNhiB9PhuNhuan** [comment]
21h-22h30

**Comment by BaoNhiB9PhuNhuan** [comment]
### **REACT NHIỀU GIỜ ĐƯỢC NHAAAAAA**

**Comment by BaoNhiB9PhuNhuan** [comment]
@ThienBao1412 @tranquynhanh11a09 @NguyenHongDucB9 @Duong0203 nhớ react cmt nhe

**Comment by ThienBao1412** [comment]
Mần súm nghỉ súm đi mụi ngừi 😇
Mai ngủ súm thứ high học nữaaa
Đờ phờ lát react cmt siu nhanh

**Comment by tranquynhanh11a09** [comment]
làm tầm nửa sáng hoặc nửa chiều là vừa chứ làm trưa nắng, tối thì ngủ 🛌

**Comment by tranquynhanh11a09** [comment]
dư chữ r hihi

**Comment by BaoNhiB9PhuNhuan** [comment]
okeee mình làm sớm nghỉ sớm nha

**Comment by BaoNhiB9PhuNhuan** [comment]
ai có mặt điểm danh nè

**Comment by tranquynhanh11a09** [comment]
cóaaaaaaaaaaa

**Comment by NguyenHongDucB9** [comment]
có nhaaa

**Comment by ThienBao1412** [comment]
Hú hú tới giờ hoạt activity ròi nè 😇

**Comment by tranquynhanh11a09** [comment]
làm này làm kia nè

**Comment by BaoNhiB9PhuNhuan** [comment]
> làm này làm kia nè
làm mình làm mẩy

**Comment by Duong0203** [comment]
có nha

**Comment by BaoNhiB9PhuNhuan** [comment]
mọi người mở sẵn tinkercard của mình nha

**Comment by BaoNhiB9PhuNhuan** [comment]
mọi người dô tinker tạo Circuit trong activity mới nha

**Comment by tranquynhanh11a09** [comment]
breadboard

**Comment by BaoNhiB9PhuNhuan** [comment]
mn tự thêm cái breadboard với mạch Adruino nha

**Comment by BaoNhiB9PhuNhuan** [comment]
ai xong tới đây thì hú lên tiếng nha

**Comment by NguyenHongDucB9** [comment]
thêm rồi nè

**Comment by ThienBao1412** [comment]
Doneee đã add thêm ổ bánh mì với áu đu nồ ròi nhó :)))

**Comment by tranquynhanh11a09** [comment]
ê là làm mấy đèn z

**Comment by tranquynhanh11a09** [comment]
làm 1 đèn led sáng thui hay 3 đèn như đèn giao thông zọ

**Comment by BaoNhiB9PhuNhuan** [comment]
tutu để hỏi lại thầy nha

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @Duong0203 xong tới bước kia chưa

**Comment by tranquynhanh11a09** [comment]
> ai xong tới đây thì hú lên tiếng nha

xong roài

**Comment by Duong0203** [comment]
oke nhó vậy mấy đèn sáng v

**Comment by BaoNhiB9PhuNhuan** [comment]
thầy chưa rep

**Comment by BaoNhiB9PhuNhuan** [comment]
hình như là 3 đèn mỗi đèn sáng 2s tắt 1s á

**Comment by BaoNhiB9PhuNhuan** [comment]
z giờ làm 1 đèn thử trước nha

**Comment by Duong0203** [comment]
đỏ vàng xanh là đèn đỏ trước nha mấy bạn

**Comment by NguyenHongDucB9** [comment]
cột đèn giao thông theo thứ tự đỏ vàng xanh nha mấy fr:))

**Comment by ThienBao1412** [comment]
Người thành công luôn có lối đi riêng , nên mình làm đèn vàng trước đi mấy anh chị em :)))

**Comment by BaoNhiB9PhuNhuan** [comment]
oke đèn đỏ trc nha

**Comment by BaoNhiB9PhuNhuan** [comment]
mở file PHT bài 6 bài 7 lên i

**Comment by BaoNhiB9PhuNhuan** [comment]
https://hiencaophunhuan.notion.site/
dô K11 lấy PHT nha

**Comment by NguyenHongDucB9** [comment]
ủa lấy đèn bỏ vô ô nào dãyyyy

**Comment by BaoNhiB9PhuNhuan** [comment]
thống nhất chung 1 chỗ để lát làm cho dễ nha

**Comment by ThienBao1412** [comment]
Để xa quá làm 3 đèn khum đủ áaa

**Comment by BaoNhiB9PhuNhuan** [comment]
z để đèn đỏ ở I 9 10 cho cao cao xa xa xíu nha

**Comment by NguyenHongDucB9** [comment]
oki nun

**Comment by ThienBao1412** [comment]
Giờ lấy cục Resisto gắn típ zô mạch ii mụi ngừii

**Comment by NguyenHongDucB9** [comment]
thíu r bảo ơi

**Comment by NguyenHongDucB9** [comment]
bịp nha:))

**Comment by tranquynhanh11a09** [comment]
lấy cái resistor nói từ cực dương ở trên xún cái chân đèn i

**Comment by BaoNhiB9PhuNhuan** [comment]
z lấy Resistor nối với cực dương nha

**Comment by BaoNhiB9PhuNhuan** [comment]
có ai chưa biết cực dương là cực nào hong

**Comment by ThienBao1412** [comment]
Ờ ha tor là phải có e rờ :)))) m ảo thuật t xong kêu t bịpp , đúng là Đức bịp có khác

**Comment by BaoNhiB9PhuNhuan** [comment]
cực dương là bên cái chân quẹo quẹo á

**Comment by ThienBao1412** [comment]
Cái cực bên phải mà nó cong cong vẹo vẹo :)))

**Comment by BaoNhiB9PhuNhuan** [comment]
tự ngẫm nghĩ xíu nha mn

**Comment by BaoNhiB9PhuNhuan** [comment]
thầy trl 3 màu nhaaaa

**Comment by tranquynhanh11a09** [comment]
ê hay h coi với bàn chung với tmay thui, chờ chị t về t mượn lap của bả làm sau chứ tự tiện lấy của bả là tí tmay ấn F để t siêu thoát luôn á
![image](https://user-images.githubusercontent.com/91965972/141666363-5910b228-41e1-40f7-b5f0-1cdb5dd5b0c4.png)

**Comment by tranquynhanh11a09** [comment]
https://huynhrom.wordpress.com/2020/04/15/1-3-2-3-den-led-sang-luan-phien/ 
ngó cái link này thử đi mn

**Comment by BaoNhiB9PhuNhuan** [comment]
thời gian trôi cũng khá lâu rồi

**Comment by BaoNhiB9PhuNhuan** [comment]
okeee hong mn

**Comment by NguyenHongDucB9** [comment]
https://youtu.be/w4m-yPBTlgU
lên đây coi nè mng

**Comment by BaoNhiB9PhuNhuan** [comment]
ủa sao cái Resistor clip đó nó nối cực âm z

**Comment by ThienBao1412** [comment]
Nó bị ngược so với cái của thầy z tar

**Comment by tranquynhanh11a09** [comment]
![image](https://user-images.githubusercontent.com/91965972/141668366-02dcca63-008a-4ee5-b896-0ef2118ab19f.png)

nè nó chạy luân phiên dc rùi á

**Comment by tranquynhanh11a09** [comment]
![image](https://user-images.githubusercontent.com/91965972/141668433-c17296b9-5346-45ad-b7b2-21ee5be117cc.png)
 gửi ké làm bằng chứng nha hok tí thoát ga cái nó mất hihi

**Comment by BaoNhiB9PhuNhuan** [comment]
à thôi mọi người đi ăn cơm nha

**Comment by BaoNhiB9PhuNhuan** [comment]
chiều tụi mình làm tiếp

**Comment by BaoNhiB9PhuNhuan** [comment]
7h tối được honggg mọi người

**Comment by tranquynhanh11a09** [comment]
ókeeeee

**Comment by Duong0203** [comment]
oke

**Comment by NguyenHongDucB9** [comment]
mng ơi tối nay cho tui xin vô trễ 15p nha

**Comment by BaoNhiB9PhuNhuan** [comment]
z cỡ 7h10-7h15 mình bắt đầu nhaaaaa mn 
@tranquynhanh11a09 @NguyenHongDucB9 @ThienBao1412 @Duong0203

**Comment by BaoNhiB9PhuNhuan** [comment]
### **aluuuuu ai có mặt điểm danh đeeeeee**

**Comment by NguyenHongDucB9** [comment]
có mặt

**Comment by ThienBao1412** [comment]
Hê hê sin trào có tui ròai đây

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @Duong0203 đâu ùi

**Comment by BaoNhiB9PhuNhuan** [comment]
hú hú 7h22 ròi mn ơi

**Comment by BaoNhiB9PhuNhuan** [comment]
mọi người ai tạo xong cái circuit có cái breadboard với mạch Adruino thì react nha

**Comment by BaoNhiB9PhuNhuan** [comment]
Do Quỳnh Anh có việc đột xuất phải đến bệnh viện với GitHub của Dương bị lỗi gì á hong vào được

**Comment by BaoNhiB9PhuNhuan** [comment]
### **Nên dời sang trưa mai sau tiết lý**

**Comment by BaoNhiB9PhuNhuan** [comment]
### **mong mọi người đúng giờ và có mặt đầy đủ**

**Comment by ThienBao1412** [comment]
Dạ oce Bnhi 🙆

**Comment by NguyenHongDucB9** [comment]
ok nha

**Comment by Duong0203** [comment]
oke

**Comment by tranquynhanh11a09** [comment]
xin lỗi mn t bận mà t không báo trước làm mn chờ, ảnh hưởng tới mn.

**Comment by BaoNhiB9PhuNhuan** [comment]
chuẩn bị nhaaaa mọi người

**Comment by BaoNhiB9PhuNhuan** [comment]
ding dongggg đến giờ roi nèe

**Comment by BaoNhiB9PhuNhuan** [comment]
Đỉm danhhh hú hú

**Comment by NguyenHongDucB9** [comment]
zô zzo

**Comment by NguyenHongDucB9** [comment]
có Đức nhá

**Comment by ThienBao1412** [comment]
Hế hế có có 🙋

**Comment by Duong0203** [comment]
co Zuong nha

**Comment by tranquynhanh11a09** [comment]
cóa

**Comment by BaoNhiB9PhuNhuan** [comment]
mọi người ai tạo xong cái circuit có cái breadboard với mạch Adruino thì react nha

**Comment by NguyenHongDucB9** [comment]
ok

**Comment by Duong0203** [comment]
có tạo gòi nhoa

**Comment by ThienBao1412** [comment]
Cí nì hum qua mình làm tới ròi mình đi hỏi thầy nè :)))

**Comment by NguyenHongDucB9** [comment]
giờ mình làm 3 đèn theo thứ tự đỏ vàng xanh nhá

**Comment by BaoNhiB9PhuNhuan** [comment]
giờ lấy 1 lần 3 cái đèn lunn iii nha

**Comment by BaoNhiB9PhuNhuan** [comment]
lấy 3 cái điện trở lun á

**Comment by ThienBao1412** [comment]
Lấy 3 đèn ii mng xong đổi màu cho nó thành đỏ vàng xanh í mụi ngừi xong với cái resistor hum qua tui nói thíu chữ e rờ á là đủ đồ dùng rùi

**Comment by ThienBao1412** [comment]
Núi đèn sao eiu Đức chỉ ii

**Comment by NguyenHongDucB9** [comment]
giờ nối cực âm ba đèn với chân GND nhe

**Comment by Duong0203** [comment]
lấy 3 chân cực âm của đèn với cái chân GND

**Comment by NguyenHongDucB9** [comment]
bik nối không đó bảo

**Comment by BaoNhiB9PhuNhuan** [comment]
mà nhớ tạo cái đó trong circuit của activiti mới nha

**Comment by BaoNhiB9PhuNhuan** [comment]
tạo lộn là thầy ko chấp nhận đâu đó

**Comment by ThienBao1412** [comment]
> bik nối không đó bảo

Cực âm nào :))) nó tới 3 chân GND đó bé :)))))

**Comment by tranquynhanh11a09** [comment]
nối với cùng 1 chân GND cũng dc

**Comment by Duong0203** [comment]
rồi lấy cái chân nào:))

**Comment by NguyenHongDucB9** [comment]
ủa có 2 chân GND th mà bảo

**Comment by ThienBao1412** [comment]
> ủa có 2 chân GND th mà bảo

2 chân ở gần với 1 chân đối diện lận mà 🤷🤷🤷

**Comment by BaoNhiB9PhuNhuan** [comment]
nối cùng 1 chân đc á

**Comment by BaoNhiB9PhuNhuan** [comment]
![image](https://user-images.githubusercontent.com/91976088/141719284-680fff5a-ba67-4f9b-ba6e-1339f005035c.png)

**Comment by BaoNhiB9PhuNhuan** [comment]
giống z nè

**Comment by NguyenHongDucB9** [comment]
oh hay quá z để tui làm theo:))

**Comment by Duong0203** [comment]
uhmmm

**Comment by ThienBao1412** [comment]
À là chân GND ở dưới kế cái Vin phớ hôn

**Comment by BaoNhiB9PhuNhuan** [comment]
được hết honggg á mọi người

**Comment by Duong0203** [comment]
hợp lý nè

**Comment by BaoNhiB9PhuNhuan** [comment]
> À là chân GND ở dưới kế cái Vin phớ hôn

chân GND nào cũng đc hết á

**Comment by Duong0203** [comment]
làm 2 chân thấy nó rối rối kiểu gì

**Comment by ThienBao1412** [comment]
Úi giời ơi 3 chân làm cứ lộn xà xộn

**Comment by ThienBao1412** [comment]
> được hết honggg á mọi người

+1 doneee

**Comment by Duong0203** [comment]
h nối 3 cái điện trở vô cực dương phải khum nhỉ

**Comment by NguyenHongDucB9** [comment]
đúng z:

**Comment by BaoNhiB9PhuNhuan** [comment]
đruiii á

**Comment by NguyenHongDucB9** [comment]
ủa mà có cần chỉnh điện trở bao nhiêu ohm ko

**Comment by Duong0203** [comment]
okey mn nhá

**Comment by ThienBao1412** [comment]
Úi giồi ôi mng đẳnk cấkp tkế

**Comment by Duong0203** [comment]
mà khoan

**Comment by ThienBao1412** [comment]
Cái điện trở 2 đầu lận zị đầu còn lại núi đi đâu zị mụi ngừi

**Comment by Duong0203** [comment]
dừng khoản chừng là 2s mình nối vào cái điện trở nào cơ

**Comment by tranquynhanh11a09** [comment]
nối dô cực dương của đèn với 1 đầu nối vô chân của mạch arduino é

**Comment by tranquynhanh11a09** [comment]
chân nèo cũng dc

**Comment by ThienBao1412** [comment]
> ủa mà có cần chỉnh điện trở bao nhiêu ohm ko

Điện trở nó cho chỉnh tên zới màu mè hoa lá hẹ cho đẹp hoi mà chỉnh ohm sao zị , hay làm Lý nhìu quá em Đức bị Lú rỏi zạy ạaa

**Comment by ThienBao1412** [comment]
> dừng khoản chừng là 2s mình nối vào cái điện trở nào cơ
> 

Thì điện chở nào cũm được nhak :)))) xắp xếp ngay ngắn đẹp đẽ là thầy cho 💯 à

**Comment by BaoNhiB9PhuNhuan** [comment]
rùi được chuaaaa á mọi người

**Comment by BaoNhiB9PhuNhuan** [comment]
![image](https://user-images.githubusercontent.com/91976088/141720004-417824c1-2c4d-4d84-83c9-3ece4c7ac9ae.png)
z đúng hongg

**Comment by tranquynhanh11a09** [comment]
rùi nạ

**Comment by Duong0203** [comment]
đúng vạy

**Comment by ThienBao1412** [comment]
> rùi được chuaaaa á mọi người

+1 donee thêm lần nữaaaa 
Zị là xong roài phớ hôn , hehe đi ngủ

**Comment by tranquynhanh11a09** [comment]
t nối giống giống z nma cũng khác khác á

**Comment by NguyenHongDucB9** [comment]
đúng đúng a nhi chỉnh màu dây lại tí cho đẹp

**Comment by BaoNhiB9PhuNhuan** [comment]
> đúng đúng a nhi chỉnh màu dây lại tí cho đẹp

aukeeee

**Comment by NguyenHongDucB9** [comment]
> t nối giống giống z nma cũng khác khác á

:)) câu nói đáng suy ngẫm

**Comment by ThienBao1412** [comment]
> đúng đúng a nhi chỉnh màu dây lại tí cho đẹp
> 

A Đức bỏ e đi theo a nhi hã seo hỏi hong trl dọ 🥺

**Comment by BaoNhiB9PhuNhuan** [comment]
mọi người xong mạch chưaaaa á

**Comment by BaoNhiB9PhuNhuan** [comment]
để mình qua code

**Comment by Duong0203** [comment]
xong rùi nè

**Comment by ThienBao1412** [comment]
> để mình qua code

Ũa làm tưởng xong roài định tắt máy đi ngủuu 🤦

**Comment by BaoNhiB9PhuNhuan** [comment]
code nha

**Comment by ThienBao1412** [comment]
Viết code như lập chình diên luôn 
Mốt đi làm lương tháng trăm củ 💲💲💲

**Comment by tranquynhanh11a09** [comment]
cí code chọn trong blocks cho dễ hỉu dc hong 🤨

**Comment by BaoNhiB9PhuNhuan** [comment]
t nghĩ làm giống cái clip hqua á

**Comment by tranquynhanh11a09** [comment]
> Viết code như lập chình diên luôn Mốt đi làm lương tháng trăm củ heavy_dollar_signheavy_dollar_signheavy_dollar_sign

![image](https://user-images.githubusercontent.com/91965972/141720416-42a9f9a3-555d-4dde-bbe0-3dfac5ec9496.png)

**Comment by ThienBao1412** [comment]
> cí code chọn trong blocks cho dễ hỉu dc hong 🤨

Làm cí nèo nhanhhh 🤷 copy paste lại dòng lệnh cũ trong text hay enblock nhanh hơn

**Comment by Duong0203** [comment]
hack được mọi cây đèn giao thông à:))

**Comment by tranquynhanh11a09** [comment]
z là khỏi bị pikachu bắt vì vượt đèn đỏ nữa

**Comment by Duong0203** [comment]
hacker lỏ men:))

**Comment by tranquynhanh11a09** [comment]
đèn đầu sáng 2s tắt 1s rồi mới đèn tiếp theo sáng 2s tắt 1s hả

**Comment by ThienBao1412** [comment]
> > Viết code như lập chình diên luôn Mốt đi làm lương tháng trăm củ heavy_dollar_signheavy_dollar_signheavy_dollar_sign
> 
> ![image](https://user-images.githubusercontent.com/91965972/141720416-42a9f9a3-555d-4dde-bbe0-3dfac5ec9496.png)
> 

Á à du tính hách phây bút me để xem trộm tin nhắn và ảnh dìm củ me với ngừi iu phớ hôn báo công an mạng bắt du nèeee

**Comment by BaoNhiB9PhuNhuan** [comment]
![image](https://user-images.githubusercontent.com/91976088/141720606-aebc52d6-ad89-4d67-8eca-8c58cd78da86.png)

**Comment by BaoNhiB9PhuNhuan** [comment]
giống z ròi đổi mấy cái set pin đúng hongg

**Comment by tranquynhanh11a09** [comment]
low là xún 0V là nó tắt he

**Comment by BaoNhiB9PhuNhuan** [comment]
rùi chỉnh 2s là high, 1s là low

**Comment by ThienBao1412** [comment]
> giống z ròi đổi mấy cái set pin đúng hongg

Đổi thêm cái hai với lâu nữaaaa

**Comment by Duong0203** [comment]
hóa ra là vậy

**Comment by Duong0203** [comment]
hèn chi nãy giờ t làm đèn chớp tắt lin tục

**Comment by ThienBao1412** [comment]
![Screenshot_2021-11-15-07-41-45-103_com.microsoft.teams.jpg](https://user-images.githubusercontent.com/91998962/141720779-355d0e31-44e6-4b62-a376-a0f4c6ac2113.jpg)
Sin trào ❤️ eiu tui đây

**Comment by NguyenHongDucB9** [comment]
nhớ chỉnh đúng chân nha mấy bae

**Comment by NguyenHongDucB9** [comment]
> ![Screenshot_2021-11-15-07-41-45-103_com.microsoft.teams.jpg](https://user-images.githubusercontent.com/91998962/141720779-355d0e31-44e6-4b62-a376-a0f4c6ac2113.jpg) Sin trào ❤️ eiu tui đây

qq gì dãy

**Comment by tranquynhanh11a09** [comment]
ồ tố kê trang trí nữa cho đẹp dc hong

**Comment by BaoNhiB9PhuNhuan** [comment]
xong code chưa zzzz

**Comment by NguyenHongDucB9** [comment]
alo:))

**Comment by BaoNhiB9PhuNhuan** [comment]
xong chưa mọi người

**Comment by BaoNhiB9PhuNhuan** [comment]
ai xong thì gửi thành quả dô đây nha

**Comment by BaoNhiB9PhuNhuan** [comment]
gửi mạch với code lun nghennn

**Comment by tranquynhanh11a09** [comment]
> xong code chưa zzzz

ê nó sáng rùi sáng như màn hình đt mẹ t lun 
![image](https://user-images.githubusercontent.com/91965972/141720936-3b5d4be1-ab0f-4e7c-9e24-d81ed3b75d1c.png)

**Comment by BaoNhiB9PhuNhuan** [comment]
ròi gửi iii nhoa

**Comment by Duong0203** [comment]
ô kìa sai chỗ méo gì mà nó tắt mịa lun gòi

**Comment by ThienBao1412** [comment]
Đợi xíu eiu Đức đang gửi đi :))

**Comment by BaoNhiB9PhuNhuan** [comment]
![image](https://user-images.githubusercontent.com/91976088/141721156-db5960c3-0c0f-4d47-aa19-b0b46a02822b.png)
![image](https://user-images.githubusercontent.com/91976088/141721204-aaa03a2b-9419-4a9c-8e7c-56a7a70d53a3.png)

**Comment by BaoNhiB9PhuNhuan** [comment]
của Bnhi nè

**Comment by BaoNhiB9PhuNhuan** [comment]
> ô kìa sai chỗ méo gì mà nó tắt mịa lun gòi

chụp gửi thử coiii

**Comment by ThienBao1412** [comment]
![image](https://user-images.githubusercontent.com/91998962/141721238-65826902-3d45-47b7-9767-0df141a54e92.png)
Há há kí tên : Bảo Châu

**Comment by BaoNhiB9PhuNhuan** [comment]
xong thì chụp gửi nhaaa

**Comment by tranquynhanh11a09** [comment]
![tin](https://user-images.githubusercontent.com/91965972/141721349-c52d9b55-5f68-469b-b850-a1dd44ee9000.png)

**Comment by BaoNhiB9PhuNhuan** [comment]
ai hong đc thì gửi rùi tụi tui coi choa

**Comment by tranquynhanh11a09** [comment]
tặng mỗi ng nhóm mình 1 bông hồng zới thầy 1 bông nữa

**Comment by NguyenHongDucB9** [comment]
![image](https://user-images.githubusercontent.com/91998895/141721481-5c9c6342-4d99-46f5-8666-ab00dbb315de.png)

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @Duong0203  được hongg

**Comment by ThienBao1412** [comment]
> ![image](https://user-images.githubusercontent.com/91998962/141721238-65826902-3d45-47b7-9767-0df141a54e92.png)
> Há há kí tên : Bảo Châu

Ủa ơ kìa chết lộn , kí tên : Bảo Bảo

**Comment by Duong0203** [comment]
được

**Comment by Duong0203** [comment]
đợi xíu

**Comment by BaoNhiB9PhuNhuan** [comment]
okokkk, hong sáng thì gửi dô tụi t check cho

**Comment by BaoNhiB9PhuNhuan** [comment]
của mn sáng đèn hết honggg

**Comment by Duong0203** [comment]
![Uploading AD069204-82D2-4FD0-B28B-616C8C93D782.jpeg…]()

**Comment by Duong0203** [comment]
Ô kìa

**Comment by tranquynhanh11a09** [comment]
> > xong code chưa zzzz
> 
> ê nó sáng rùi sáng như màn hình đt mẹ t lun ![image](https://user-images.githubusercontent.com/91965972/141720936-3b5d4be1-ab0f-4e7c-9e24-d81ed3b75d1c.png)

nè =)))) rất sáng lun

**Comment by BaoNhiB9PhuNhuan** [comment]
z @Duong0203 gửi mess cho t đi

**Comment by BaoNhiB9PhuNhuan** [comment]
t up lên đây giùm cho

**Comment by ThienBao1412** [comment]
> ![Uploading AD069204-82D2-4FD0-B28B-616C8C93D782.jpeg…]()
> 

Ảo thật đấyyyy

**Comment by Duong0203** [comment]
lừa thế nhò

**Comment by NguyenHongDucB9** [comment]
> okokkk, hong sáng thì gửi dô tụi t check cho

sáng bth nè

**Comment by BaoNhiB9PhuNhuan** [comment]
![image](https://user-images.githubusercontent.com/91976088/141721895-67f5a9e5-2288-438c-a736-f91c05618292.png)

**Comment by ThienBao1412** [comment]
> của mn sáng đèn hết honggg

Sáng như trăng rằm tháng 7 👻👻

**Comment by Duong0203** [comment]
ẻo thật đấy

**Comment by BaoNhiB9PhuNhuan** [comment]
của zương nha

**Comment by BaoNhiB9PhuNhuan** [comment]
mọi người oke hết rùi đúng hơm

**Comment by Duong0203** [comment]
ẻo thật

**Comment by BaoNhiB9PhuNhuan** [comment]
đèn sáng như vầng trăng hết ròi đúng hongg

**Comment by BaoNhiB9PhuNhuan** [comment]
z nghỉ đi ăn trưa nhoaaaa

**Comment by BaoNhiB9PhuNhuan** [comment]
cảm ơn mọi người

**Comment by ThienBao1412** [comment]
> mọi người oke hết rùi đúng hơm

Sáng là xong rùi phớ hôn , đi ngủ eiu @NguyenHongDucB9  ơi ơi

**Comment by NguyenHongDucB9** [comment]
mng ăn trưa ngon miệng

**Comment by BaoNhiB9PhuNhuan** [comment]
lát t tổng hợp lại ròi 3h dô đây react nha

**Comment by NguyenHongDucB9** [comment]
> > mọi người oke hết rùi đúng hơm
> 
> Sáng là xong rùi phớ hôn , đi ngủ eiu @NguyenHongDucB9 ơi ơi

th tha e

**Comment by tranquynhanh11a09** [comment]
ủa ê cho hỏi i

**Comment by ThienBao1412** [comment]
Tuck in 
Bon appetite 
Mng ăn trưa ngon miệng 
Tui học Tiếng Anh dở nhưng ngiu chúc quài nên cũng biết nhaaa

**Comment by Duong0203** [comment]
pp mn

**Comment by tranquynhanh11a09** [comment]
giờ t muốn điều chỉnh độ sáng của đèn thì sao z

**Comment by ThienBao1412** [comment]
> lát t tổng hợp lại ròi 3h dô đây react nha

Ố kề để đặt béo thức , mng ngủ ngon luôn nhó

**Comment by ThienBao1412** [comment]
> > > mọi người oke hết rùi đúng hơm
> > 
> > Sáng là xong rùi phớ hôn , đi ngủ eiu @NguyenHongDucB9 ơi ơi
> 
> th tha e

Đi thoi eiu 3h mình quay lại

**Comment by ThienBao1412** [comment]
> giờ t muốn điều chỉnh độ sáng của đèn thì sao z

Để bữa khác đi 😏 h teo với eiu @NguyenHongDucB9  đi ngủ ròi
Bữa sau thầy giảng cho nhó gút midafternoon

**Comment by BaoNhiB9PhuNhuan** [comment]
> giờ t muốn điều chỉnh độ sáng của đèn thì sao z

@HienCaoPhuNhuan học trò hỏi nè thầy

**Comment by BaoNhiB9PhuNhuan** [comment]
### **TỔNG KẾT:**
### **1️⃣ Vật liệu:**
- 1 bảng mạch Adruino Uno R3
- 1 breadboard
- 3 đèn Led (1 red,1 yellow, 1 green)
- 3 resistor
### **2️⃣ Thực hiện lắp mạch:**
- Nối chân cực âm của 3 đèn với 1 chân GND
- Nối chân cực dương của 3 đèn với 3 resistor
- Nối chân còn lại của resistor với mạch Adruino
👇Minh họa như hình bên dưới
![image](https://user-images.githubusercontent.com/91976088/141738342-3813a454-ed8d-474f-b1a2-109d1707127c.png)
### **3️⃣ Lập code:**
👇Như hình bên dưới
![image](https://user-images.githubusercontent.com/91976088/141738482-4f5bd5b0-b3e9-4169-923f-a600b34c613a.png)
### **4️⃣ Kết quả:**
👇Nhấn vào link bên dưới
https://app.vmaker.com/record/F0TNeR3B3N8Knhrp

**Comment by BaoNhiB9PhuNhuan** [comment]
@tranquynhanh11a09 @NguyenHongDucB9 @ThienBao1412 @Duong0203 nhớ 3h dô react nhooooo

**Comment by BaoNhiB9PhuNhuan** [comment]
@HienCaoPhuNhuan Nhóm 6 - 11A09 xong nhiệm vụ tuần này ròi nhaaa thầy

**Comment by HienCaoPhuNhuan** [comment]
> giờ t muốn điều chỉnh độ sáng của đèn thì sao z

Mình mới học digital à con, chưa analog, tutu
